version: '2'
services:
  # shortener:
  #   container_name: shortener
  #   image: duzhen/shortener
  #   links:
  #     - mongodb
  #     - redis
  #     - kafka
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - mongodb
  #     - redis
  #     - kafka
  #   environment:
  #     NODE_ENV: production
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null
    network_mode: host
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
    network_mode: host
  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "SHORTENER:1:1"
      KAFKA_HEAP_OPTS: "-Xmx256M -Xms128M"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: host
  redis:
    image: redis
    ports:
      - "6379:6379"
    network_mode: host